#' Helpers for supplying SMTP credentials
#'
#' These helper functions, the credential helpers, are used to supply SMTP
#' configuration and authorization information for the [smtp_send()] function.
#' These helpers ([creds_file()], [creds_key()], and [creds()]) are to be used
#' expressly with the `credentials` argument of [smtp_send()]. The
#' [creds_file()] credential helper is used to point at a credentials file
#' stored on disk. We can create that file using the [create_smtp_creds_file()]
#' function. The [creds_key()] credential helper is truly somthing special. It
#' actually helps one obtain credentials that are stored in the system-wide
#' key-value store. The equally magical [create_smtp_creds_key()] function sets
#' that key. Using [creds()] allows for manual specification of SMTP
#' configuration and authentication within that helper function.
#'
#' @param file When using the [creds_file()] credential helper, we need to
#'   specify the location of the credential file, and, this is where that is
#'   done. The credential file was ideally generated by the
#'   [create_smtp_creds_file()] function.
#' @param key_name When using the [creds_key()] credential helper, the name of
#'   the key (in the system key-value store) needs to be given here. This was
#'   either explicitly provided when using the [create_smtp_creds_key()]
#'   function (with its own `key_name` argument), or, it may have been
#'   automatically generated based on the SMTP host name.
#' @inheritParams create_smtp_creds_file
#' @name credential_helpers
#' @return a list object of class `location_cells`.
NULL

#' Credentials helper for pointing to a SMTP credentials file
#'
#' @rdname credential_helpers
#' @export
creds_file <- function(file) {

  structure(
    class = c("creds_file", "blastula_creds"),
    list(
      file = file
    )
  )
}

#' Credentials helper for pointing to a SMTP credentials key
#'
#' @rdname credential_helpers
#' @export
creds_key <- function(key_name) {

  structure(
    class = c("creds_key", "blastula_creds"),
    list(
      key_name = key_name
    )
  )
}

#' Credentials helper for manual entry of SMTP config and auth values
#'
#' @rdname credential_helpers
#' @export
creds <- function(provider = NULL,
                  user,
                  sender_name = NULL,
                  host = NULL,
                  port = NULL,
                  use_ssl = TRUE) {

  # Create a credentials list from the function inputs
  credentials_list <-
    create_credentials_list(
      provider = provider,
      user = user,
      sender_name = sender_name,
      host = host,
      port = port,
      use_ssl = use_ssl
    )

  structure(
    class = c("creds", "blastula_creds"),
    credentials_list
  )
}
