#' Create a file with email access credentials
#'
#' Create a file with access credentials for the purpose of more easily sending
#' email messages through [smtp_send()].
#'
#' @param file_name An option to specify a name for the credentials file.
#'   If no name is provided, one will be automatically generated. The
#'   autogenerated file will be invisible and have its name constructed in the
#'   following way: `blastula-<host_name>`.
#' @param provider An optional provider email provider with which an STMP
#'   account is available. Options currently include `gmail`, `outlook`, and
#'   `office365`. If nothing is provided then values for `host`, `port`,
#'   `sender`, `use_ssl`, `use_tls`, and `authenticate` are expected.
#' @param user The username for the email account.
#' @param sender_name The sender name.
#' @param host The `host` name.
#' @param port The port number.
#' @param use_ssl An option as to whether to use SSL; supply a `TRUE` or `FALSE`
#'   value (`TRUE` is the default value).
#' @param ... The `...` is unused and only serves to force the naming of
#'   subsequent argument (`password`) and avoid an unintended use.
#' @param password The password for the SMTP server. Normally, in interactive
#'   use, this doesn't need to be provided here. Rather, a dialog box will
#'   appear asking for the password (which is masked and never enters the
#'   `.Rhistory` file). This argument is provided here just in case the function
#'   needs to be used non-interactively.
#' @examples
#' \dontrun{
#' # Create a credentials file to facilitate
#' # the sending of email messages
#' create_smtp_creds_file(
#'   provider = "gmail"
#'   user = "user_name@gmail.com",
#'   )
#' }
#' @export
create_smtp_creds_file <- function(file_name = NULL,
                                   provider = NULL,
                                   user,
                                   sender_name = NULL,
                                   host = NULL,
                                   port = NULL,
                                   use_ssl = TRUE,
                                   ...,
                                   password = NULL) {

  # Ensure that `use_ssl` is either TRUE or FALSE
  if (!(use_ssl %in% c(TRUE, FALSE))) {
    stop("The value supplied to `use_ssl` must be TRUE or FALSE.")
  }

  # If a `provider` name is given, extract values for `host`,
  # `port`, `use_ssl`, `use_tls`, and `authenticate`
  if (!is.null(provider) &&
      provider %in% (smtp_settings() %>% dplyr::pull(short_name))) {

    # Extract the record for the SMTP provider
    settings_record <-
      smtp_settings() %>%
      dplyr::filter(short_name == provider)

    # TODO: only set these if the incoming values are not NULL
    # Extract settings for the provider
    host <- settings_record$server
    port <- settings_record$port
    use_ssl <- settings_record$use_ssl
  }

  credentials_list <-
    list(
      version = NA_integer_,
      sender_name = sender_name,
      host = host,
      port = port,
      use_ssl = use_ssl,
      user = user,
      password = password %||% getPass::getPass("Enter the SMTP server password: ")
    )

  if (is.null(file_name)) {

    # Construct a file name based on the `host` name
    file <- paste0("blastula-", host %>% tidy_gsub("\\.", "_"))

  } else {

    file <- as.character(file_name)
  }

  # Save the credential values as an RDS file
  saveRDS(credentials_list, file = file)

  # Issue a message stating that the file has been created
  message("The SMTP credentials file (`", file, "`) has been generated")
}

#' Store SMTP credentials in the system's key-value store
#'
#' Set SMTP access credentials using the **keyring** package.
#' @inheritParams create_smtp_creds_file
#' @examples
#' \dontrun{
#' # Store SMTP crendentials using the system's
#' # secure key-value store
#' create_smtp_creds_key(
#'   provider = "gmail",
#'   user = "user_name@gmail.com",
#'   )
#' }
#' @export
create_smtp_creds_key <- function(key_name = NULL,
                                  provider = NULL,
                                  user,
                                  sender_name = NULL,
                                  host = NULL,
                                  port = NULL,
                                  use_ssl = TRUE,
                                  ...,
                                  password = NULL) {

  if (!keyring::has_keyring_support()) {
    stop("To store SMTP via *keyring*, the system needs to have",
         "*keyring* support", call. = FALSE)
  }

  # Ensure that `use_ssl` is either TRUE or FALSE
  if (!(use_ssl %in% c(TRUE, FALSE))) {
    stop("The value supplied to `use_ssl` must be TRUE or FALSE.")
  }

  if (!is.null(provider) &&
      provider %in% (smtp_settings() %>% dplyr::pull(short_name))) {

    # Extract the record for the SMTP provider
    settings_record <-
      smtp_settings() %>%
      dplyr::filter(short_name == provider)

    # TODO: only set these if the incoming values are not NULL
    # Extract settings for the provider
    host <- settings_record$server
    port <- settings_record$port
    use_ssl <- settings_record$use_ssl
  }

  # If the `sender_name` isn't provided, use
  # an empty string
  if (is.null(sender_name)) sender_name <- ""

  # Use the provider name if it's given as the
  # `key_name` (if that's not given)
  if (is.null(key_name) && !is.null(provider)) {
    key_name <- provider
  } else if (is.null(key_name)) {
    key_name <- ""
  }

  # Create the `service_name` for `keyring`
  service_name <- paste0("blastula-v", keyring_schema_version, "-", key_name)

  credentials_list <-
    list(
      version = keyring_schema_version,
      sender_name = sender_name,
      host = host,
      port = port,
      use_ssl = use_ssl,
      user = user,
      password = password %||% getPass::getPass("Enter the SMTP server password: ")
    )

  serialized <-
    credentials_list %>%
    jsonlite::serializeJSON() %>%
    as.character()

  # Set the key in the system's default keyring
  keyring::key_set_with_value(
    service = service_name,
    user = user,
    password = serialized
  )

  # Issue a message stating that the file has been created
  message("The system key store has been updated with the (`", service_name, "`) key.")
}

#' Utility function for obtaining keyring entries related to blastula creds
#'
#' @import keyring
#' @importFrom dplyr as_tibble filter mutate
#' @importFrom tidyr separate
#' @noRd
get_keyring_creds_table <- function(version = keyring_schema_version) {

  creds_tbl <-
    keyring::key_list() %>%
    dplyr::as_tibble() %>%
    dplyr::filter(grepl(paste0("blastula-v", version), service))

  if (nrow(creds_tbl) == 0) {

    empty_creds_tbl <-
      dplyr::tibble(
        key_name = NA_character_,
        version = NA_integer_,
        username = NA_character_
      )[-1, ]

    return(empty_creds_tbl)

  } else {

    creds_tbl <-
      creds_tbl %>%
      tidyr::separate(
        col = service,
        into = c("package", "version", "key_name"),
        sep = "-",
        remove = FALSE
      ) %>%
      dplyr::mutate(
        version = version %>%
          tidy_gsub("v", "") %>%
          as.integer()) %>%
      dplyr::select(service, key_name, version, username)
  }

  creds_tbl
}

#' Retrieve metadata and authentication values from keyring data
#'
#' @noRd
get_smtp_keyring_creds <- function(key_name = NULL) {

  # Get a filtered table of key and values that
  # are only those keys generated by the
  # `create_smtp_creds_key()` function
  blastula_keys_tbl <-
    get_keyring_creds_table() %>%
    dplyr::filter(
      key_name == key_name,
      version == keyring_schema_version
    )

  # If the given `key_name` doesn't correspond to an
  # entry in `blastula_keys_tbl`, stop the function with
  # an explanatory message
  if (nrow(blastula_keys_tbl) == 0) {
    stop("There is no blastula key that corresponds to the `key_name` of \"",
         key_name, "\".",
         call. = FALSE)
  }

  # For the given `key_name` get the key's stored value and
  # transform the JSON data to a list object
  blastula_keys_tbl %>%
    dplyr::pull(service) %>%
    keyring::key_get() %>%
    jsonlite::unserializeJSON()
}

#' Helpers for supplying SMTP credentials
#'
#' These helper functions, the credential helpers, are used to supply SMTP
#' configuration and authorization information for the [smtp_send()] function.
#' These helpers ([creds_file()], [creds_key()], and [creds()]) are to be
#' used expressly with the `credentials` argument of [smtp_send()]. The
#' [creds_file()] credential helper is used to point at a credentials file
#' stored on disk. We can create that file using the [create_smtp_creds_file()]
#' function. The [creds_key()] credential helper is truly somthing special.
#' It actually helps one obtain credentials that are stored in the system-wide
#' key-value store. The equally magical [create_smtp_creds_key()] function sets
#' that key. Using [creds()] allows for manual specification of SMTP
#' configuration and authentication within that helper function.
#'
#' @param file When using the [creds_file()] credential helper, we need to
#'   specify the location of the credential file, and, this is where that is
#'   done. The credential file was ideally generated by the
#'   [create_smtp_creds_file()] function.
#' @param key_name When using the [creds_key()] credential helper, the name of
#'   the key (in the system key-value store) needs to be given here. This was
#'   either explicitly provided when using the [create_smtp_creds_key()]
#'   function (with its own `key_name` argument), or, it may have been
#'   automatically generated based on the SMTP host name.
#' @inheritParams create_smtp_creds_file
#' @name credential_helpers
#' @return a list object of class `location_cells`.
NULL

#' Credentials helper for pointing to a SMTP credentials file
#'
#' @rdname credential_helpers
#' @export
creds_file <- function(file) {

  structure(
    class = c("creds_file", "blastula_creds"),
    list(
      file = file
    )
  )
}

#' Credentials helper for pointing to a SMTP credentials key
#'
#' @rdname credential_helpers
#' @export
creds_key <- function(key_name) {

  structure(
    class = c("creds_key", "blastula_creds"),
    list(
      key_name = key_name
    )
  )
}

#' Credentials helper for manual entry of SMTP config and auth values
#'
#' @rdname credential_helpers
#' @export
creds <- function(provider = NULL,
                  user,
                  sender_name = NULL,
                  host = NULL,
                  port = NULL,
                  use_ssl = TRUE,
                  ...,
                  password = NULL) {

  if (!is.null(provider) &&
      provider %in% (smtp_settings() %>% dplyr::pull(short_name))) {

    # Extract the record for the SMTP provider
    settings_record <-
      smtp_settings() %>%
      dplyr::filter(short_name == provider)

    # TODO: only set these if the incoming values are not NULL
    # Extract settings for the provider
    host <- settings_record$server
    port <- settings_record$port
    use_ssl <- settings_record$use_ssl
  }

  # If the `sender_name` isn't provided, use an empty string
  if (is.null(sender_name)) sender_name <- ""

  credentials_list <-
    list(
      version = NA_integer_,
      sender_name = sender_name,
      host = host,
      port = port,
      use_ssl = use_ssl,
      user = user,
      password = password %||% getPass::getPass("Enter the SMTP server password: ")
    )

  structure(
    class = c("creds", "blastula_creds"),
    credentials_list
  )
}

# Globally set the schema version for the storage
# of SMTP settings and authentication via keyring
keyring_schema_version <- 1L
