#' Retrieve metadata and authentication values from an on-disk credentials file
#'
#' @noRd
get_smtp_file_creds <- function(file_name = NULL) {

  # For the given `file_name`, read in the JSON
  # data and convert it into a list object
  readLines(file_name) %>%
    jsonlite::unserializeJSON()
}

#' Retrieve metadata and authentication values from keyring data
#'
#' @noRd
get_smtp_keyring_creds <- function(key_name = NULL) {

  # Get a filtered table of key and values that
  # are only those keys generated by the
  # `create_smtp_creds_key()` function
  blastula_keys_tbl <-
    get_keyring_creds_table() %>%
    dplyr::filter(
      key_name == key_name,
      version == schema_version
    )

  # If the given `key_name` doesn't correspond to an
  # entry in `blastula_keys_tbl`, stop the function with
  # an explanatory message
  if (nrow(blastula_keys_tbl) == 0) {
    stop("There is no blastula key that corresponds to the `key_name` of \"",
         key_name, "\".",
         call. = FALSE)
  }

  # For the given `key_name` get the key's stored value and
  # transform the JSON data to a list object
  blastula_keys_tbl %>%
    dplyr::pull(service) %>%
    keyring::key_get() %>%
    jsonlite::unserializeJSON()
}


#' Utility function for obtaining keyring entries related to blastula creds
#'
#' @import keyring
#' @importFrom dplyr as_tibble filter mutate
#' @importFrom tidyr separate
#' @noRd
get_keyring_creds_table <- function(version = schema_version) {

  creds_tbl <-
    keyring::key_list() %>%
    dplyr::as_tibble() %>%
    dplyr::filter(grepl(paste0("blastula-v", version), service))

  if (nrow(creds_tbl) == 0) {

    empty_creds_tbl <-
      dplyr::tibble(
        key_name = NA_character_,
        version = NA_integer_,
        username = NA_character_
      )[-1, ]

    return(empty_creds_tbl)

  } else {

    creds_tbl <-
      creds_tbl %>%
      tidyr::separate(
        col = service,
        into = c("package", "version", "key_name"),
        sep = "-",
        remove = FALSE
      ) %>%
      dplyr::mutate(
        version = version %>%
          tidy_gsub("v", "") %>%
          as.integer()) %>%
      dplyr::select(service, key_name, version, username)
  }

  creds_tbl
}

