on:
  push:
    branches:
     - main
     - master
  pull_request:
    branches:
     - main
     - master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GHA_PAT }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, github::rstudio/quillt, local::.
          needs: website

      - name: Install package
        run: R CMD INSTALL .

      - name: Build pkgdown site
        run: pkgdown::build_site(new_process = FALSE)
        shell: Rscript {0}

      - name: Git setup
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Deploy package
        if: ${{ github.event_name == 'push' || startsWith(github.head_ref, 'pkgdown/') }}
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}

      - name: Deploy to Netlify
        if: ${{ github.event_name == 'push' || startsWith(github.head_ref, 'pkgdown/') }}
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v1.1
        # NETLIFY_AUTH_TOKEN added in the repo's secrets
        with:
          publish-dir: 'docs'
          production-branch: master
          github-token: ${{ secrets.GHA_PAT }}
          deploy-message:
            'Deploy from GHA: ${{ github.event.head_commit.message }} (${{ github.sha }})'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
          alias: deploy-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
